services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
      - ./application.log:/usr/share/logstash/logs
    ports:
      - "5044:5044"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
